In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [2]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [3]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [4]:
# don't do this use a loop instead, anytime I see repetitve code I think they should have used a loop
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [5]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.964
Model:                            OLS   Adj. R-squared:                  0.961
Method:                 Least Squares   F-statistic:                     410.4
Date:                Tue, 30 Sep 2025   Prob (F-statistic):           1.30e-64
Time:                        20:14:11   Log-Likelihood:                -380.16
No. Observations:                 100   AIC:                             774.3
Df Residuals:                      93   BIC:                             792.6
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -32.7602      7.450     -4.397      0.000     -47.555     -17.965
X1             1.3537      0.128     10.594      0.000       1.100       1.607
X2             1.6240      0.058     27.785      0.000       1.508       1.740
X3             1.0662      0.094     11.287      0.000       0.879       1.254
X4             0.7971      0.141      5.664      0.000       0.518       1.077
X5            -2.0629      0.060    -34.347      0.000      -2.182      -1.944
X6            -0.8933      0.109     -8.202      0.000      -1.110      -0.677
==============================================================================
Omnibus:                        1.950   Durbin-Watson:                   1.951
Prob(Omnibus):                  0.377   Jarque-Bera (JB):                1.469
Skew:                           0.083   Prob(JB):                        0.480
Kurtosis:                       2.430   Cond. No.                         479.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [7]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [13]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.973
Model:                            OLS   Adj. R-squared (uncentered):              0.970
Method:                 Least Squares   F-statistic:                              269.0
Date:                Tue, 30 Sep 2025   Prob (F-statistic):                    7.50e-64
Time:                        20:14:49   Log-Likelihood:                         -381.51
No. Observations:                 100   AIC:                                      787.0
Df Residuals:                      88   BIC:                                      818.3
Df Model:                          12                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X1             1.2286      0.134      9.166      0.000       0.962       1.495
X2             1.6388      0.062     26.465      0.000       1.516       1.762
X3             0.9237      0.091     10.190      0.000       0.744       1.104
X4             0.5587      0.148      3.771      0.000       0.264       0.853
X5            -2.0603      0.063    -32.653      0.000      -2.186      -1.935
X6            -0.9575      0.112     -8.566      0.000      -1.180      -0.735
X7            -0.1690      0.139     -1.215      0.228      -0.446       0.107
X8            -0.0556      0.058     -0.960      0.340      -0.171       0.059
X9            -0.2821      0.099     -2.855      0.005      -0.479      -0.086
X10           -0.1809      0.143     -1.265      0.209      -0.465       0.103
X11            0.0458      0.059      0.771      0.443      -0.072       0.164
X12            0.1473      0.097      1.520      0.132      -0.045       0.340
==============================================================================
Omnibus:                        0.838   Durbin-Watson:                   1.872
Prob(Omnibus):                  0.658   Jarque-Bera (JB):                0.538
Skew:                           0.173   Prob(JB):                        0.764
Kurtosis:                       3.098   Cond. No.                         15.1
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.33522604,  1.62937691,  1.04157525,  0.69679598, -2.07220181,
       -0.84929981, -0.06842065, -0.03351382, -0.10103855, -0.0061838 ,
        0.00846681,  0.22568521])

In [10]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 1.22221761,  1.59720706,  0.99753063,  0.60033792, -2.04932393,
       -0.76413086, -0.        , -0.01705001, -0.04140385, -0.        ,
        0.        ,  0.17364998])

In [11]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.34420358,  1.6317166 ,  1.0457815 ,  0.70701247, -2.07398283,
       -0.85679921, -0.08367905, -0.03609181, -0.10941622, -0.01422878,
        0.01035887,  0.23129113])

In [17]:
model_ridge = lm.Ridge(alpha=120).fit(X_ext,y)
model_ridge.coef_

array([ 1.32127687,  1.6249313 ,  1.03911778,  0.69647566, -2.06757482,
       -0.84390982, -0.08049137, -0.03771322, -0.11318044, -0.02279446,
        0.01363299,  0.23045577])

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/delinai/schulich_ds1/refs/heads/main/Datasets/kc_house_data.csv') # clean data set

In [19]:
x = df.iloc[:,3:]
y = df['price']
x = sm.add_constant(x)

In [21]:
model_houses = sm.OLS(y,x).fit()
print(model_houses.summary())

                            OLS Regression Results                            
Dep. Variable:                  price   R-squared:                       0.700
Model:                            OLS   Adj. R-squared:                  0.700
Method:                 Least Squares   F-statistic:                     2960.
Date:                Tue, 30 Sep 2025   Prob (F-statistic):               0.00
Time:                        20:20:38   Log-Likelihood:            -2.9460e+05
No. Observations:               21613   AIC:                         5.892e+05
Df Residuals:                   21595   BIC:                         5.894e+05
Df Model:                          17                                         
Covariance Type:            nonrobust                                         
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           6.69e+06   2.93e+06      2.282

In [ ]:
x = x.iloc[:,1:]

In [32]:
housing_lasso = lm.Lasso(alpha=10).fit(x, y)
housing_lasso.coef_

array([ 1.53943403e-01,  1.70363976e+04,  5.93957582e+05,  5.60082866e+04,
        2.63947147e+04,  1.02252306e+05,  1.72688339e+02,  1.47184848e+02,
       -2.31694061e+03,  2.63725485e+01, -5.59220806e+02,  6.10821170e+05,
       -2.14254304e+05,  2.13881561e+01, -3.44417382e-01])

In [33]:
housing_lasso = lm.Lasso(alpha=10000).fit(x, y)
housing_lasso.coef_

array([-7.73490553e-03,  0.00000000e+00,  0.00000000e+00,  5.69443830e+04,
        0.00000000e+00,  1.08719492e+05,  1.80286521e+02,  1.72090297e+02,
       -3.02957446e+03,  2.71927509e+01,  9.93036383e+01,  1.19167221e+03,
       -0.00000000e+00,  2.96138460e+01, -5.45206311e-01])

In [34]:
housing_ridge = lm.Ridge(alpha=10).fit(x, y)
housing_ridge.coef_

array([ 1.47932591e-01,  1.77478188e+04,  5.54505062e+05,  5.75930895e+04,
        2.62416660e+04,  1.02828392e+05,  1.72294605e+02,  1.47640758e+02,
       -2.34416960e+03,  2.65623854e+01, -5.40891880e+02,  5.94006793e+05,
       -2.05677587e+05,  2.11726105e+01, -3.48171477e-01])

In [35]:
housing_ridge = lm.Ridge(alpha=200).fit(x, y)
housing_ridge.coef_

array([ 8.46132075e-02,  2.49248334e+04,  2.41303114e+05,  6.82203936e+04,
        2.36384104e+04,  1.09129285e+05,  1.67889906e+02,  1.54095142e+02,
       -2.66243115e+03,  2.71671697e+01, -3.19337885e+02,  3.86656377e+05,
       -1.10626505e+05,  2.05338841e+01, -4.01770817e-01])