In [1]:
import numpy as np

In [2]:
# common elements of Python
# lists, tuples, sets and dictionaries
# common operations >> conditionals, loops
# numpy operations
# common pandas operations

In [3]:
# lists --> []
list1 = [12, 15, 78, 15, 25]


In [4]:
list1.append(100)
list1

[12, 15, 78, 15, 25, 100]

In [5]:
# when you append a LIST of items you get a nested list
list1.append([100, 200])
list1

[12, 15, 78, 15, 25, 100, [100, 200]]

In [6]:
# insert a value at a specific position
list1.insert(2, 1000)
list1

[12, 15, 1000, 78, 15, 25, 100, [100, 200]]

In [7]:
# pop() or remove()
list1.pop(7)
list1

[12, 15, 1000, 78, 15, 25, 100]

In [8]:
# remove() --> first time the value occurs
list1.remove(15)

In [9]:
# index() tells you the FIRST index position of a value
list1.index(100)

5

In [10]:
# count() will tell you how many of a specific value you have
list1.count(100)

1

In [11]:
# indexing and slicing
list1[0]

12

In [12]:
# slice -- isolate a range of values
list1[3:7]

[15, 25, 100]

In [13]:
# starting position : ending position : step (2 = every other item)
list1[1:8:2]

[1000, 15, 100]

In [14]:
# lists support item assignment meaning we can overwrite values
list1[0] = 4000

In [16]:
# tuple --> defined with round brackets ()
tuple1 = (8, 7, 6, 15)

In [17]:
# count the number of elements of a certain value
tuple1.count(8)

1

In [18]:
# find the first position of a certain value
tuple1.index(15)

3

In [19]:
# you cannot overwrite or change values in a tuple
tuple1[0] = 1000

TypeError: 'tuple' object does not support item assignment

In [21]:
# setes --> {}
set1 = {12, 13, 15, 18, 25, 15, 100, 100}
set1 # sets do not hold duplicate values, even if you define one with dupes it will remove them
# can convert a list to a set and it will remove all the duplicates for you
# sets are useful when comparing/contrasting multiple data collections, not very useful by itself

{12, 13, 15, 18, 25, 100}

In [22]:
set2 = {13, 100, 18, 14, 27, 35}

In [23]:
# find common elements
set1.intersection(set2)

{13, 18, 100}

In [24]:
# find elements that exist in set 1 but not in set 2
set1.difference(set2)

{12, 15, 25}

In [26]:
set2.difference(set1) # elements in set 2 but not in set 1

{14, 27, 35}

In [27]:
# If I only want to keep elements in set2 which are different than set1
set2.difference_update(set1)
set2

{14, 27, 35}

https://docs.python.org/3/library/functions.html

In [28]:
# dictionaries
dict1 = {'ON': 'Toronto', 'MB': 'Winnipeg', 'SK': 'Regina', 'BC': 'Victoria'}


In [ ]:
dict1.keys() # all the keys of the dictionary, highest level of information in the dictionary

dict_keys(['ON', 'MB', 'SK', 'BC'])

In [30]:
dict1.values() # all the values of the dictionary

dict_values(['Toronto', 'Winnipeg', 'Regina', 'Victoria'])

In [31]:
# hierarchical data example
dict2 = {'customer1': {'books':['book1', 'book2'], 'food':['chips', 'tomatoes']}, 'customer2': {'clothing':['socks', 'shirt'], 'electronics':['tv', 'phone']}}

In [33]:
dict2.keys()

dict_keys(['customer1', 'customer2'])

In [34]:
dict2.values() # example of unstructured data

dict_values([{'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']}, {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'phone']}])

In [35]:
dict2['customer1'].keys()

dict_keys(['books', 'food'])

In [36]:
dict2['customer1'].values()

dict_values([['book1', 'book2'], ['chips', 'tomatoes']])

In [37]:
# adding a new key:value to a dictionary - just add one that doesn't exist
dict2['customer3'] = {'groceries':['chips', 'pop'], 'shoes':['running shoes', 'tennis shoes']}
dict2

{'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']},
 'customer2': {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'phone']},
 'customer3': {'groceries': ['chips', 'pop'],
  'shoes': ['running shoes', 'tennis shoes']}}

In [38]:
# removing an element, we can use pop()
dict2.pop('customer3')
dict2

{'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']},
 'customer2': {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'phone']}}

In [39]:
dict2.items()

dict_items([('customer1', {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']}), ('customer2', {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'phone']})])

In [47]:
# conditional statements
x = 9*12/14+100

In [43]:
if x > 10:
    print(f'{x} is greater than 10')
else:
    print(f'{x} is not greater than 10')

107.71428571428571 is greater than 10


In [49]:
if x > 10:
    x = (x + 15) / 22 # initial transformation
    x = x/12 # secondary transformation
else:
    print(f'{x} is not greater than 10')
print(x)

0.4648268398268398 is not greater than 10
0.4648268398268398


In [ ]:
# make sure conditions are mutually exclusive
if x > 10:
    x = (x + 15) / 22 # initial transformation
    x = x/12 # secondary transformation
    print(f'{x} is calculated')

elif x > 5 and x <= 10:
    x = (x + 10) / 12
    print(x)
else:
    x = 0
print(x)

0


In [ ]:
# looping -- the for loop
# for each item in a collection, preform some action
for i in list1: # example of a mathematical transformation
    if i > 10:
        i = (i + 15) / 22
        i = i / 12
        print(f'{i} is calculated')
    elif i > 5 and i <= 100:
        i = (i + 10) / 12
        print(i)
    else:
        i = 0

print(i)

15.208333333333334 is calculated
3.8446969696969693 is calculated
0.3522727272727273 is calculated
0.11363636363636363 is calculated
0.15151515151515152 is calculated
0.4356060606060606 is calculated
0.4356060606060606


In [54]:
for i in dict2: 
    print(i)
# only prints the keys from a dictionary/


customer1
customer2


In [56]:
for i in dict2.items():
    print(i)
# will output a tuple - the key and the dictionary

('customer1', {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']})
('customer2', {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'phone']})


In [57]:
# we can use the loop to structure the data, by isolating specific elements and structure the data so it is more useable

In [ ]:
# calculate how many items from each major category were ordered
for key, value in dict2.items():
    # need to isolate the categories (keys)
    # I need a nested dictionary
    # detupled the tuple
    for a, b in value.items(): # nested for loop which separates the category and the number of items
        print(a)
        print(b)


books
['book1', 'book2']
food
['chips', 'tomatoes']
clothing
['socks', 'shirt']
electronics
['tv', 'phone']


In [62]:
categories_w_purchases = []
items_purchased = []
num_categories = 0
num_items = 0

for key, value in dict2.items():
    for a, b in value.items():
        if a not in categories_w_purchases:
            categories_w_purchases.append(a)
            num_categories += 1
print(categories_w_purchases)
print(items_purchased)
print(num_categories)
print(num_items)


['books', 'food', 'clothing', 'electronics']
[]
4
0


In [63]:
# calculate how many items from each major category were ordered
categories_w_purchases = []
items_purchased = []
num_categories = 0
num_items = 0

for key, value in dict2.items():
  for a, b in value.items():
    if a not in categories_w_purchases:
      categories_w_purchases.append(a)
      num_categories += 1
    for item in b:
      if item not in items_purchased:
        items_purchased.append(item)
        num_items += 1

print(categories_w_purchases)
print(items_purchased)
print(num_categories)
print(num_items)

['books', 'food', 'clothing', 'electronics']
['book1', 'book2', 'chips', 'tomatoes', 'socks', 'shirt', 'tv', 'phone']
4
8


In [64]:
# calculate how many items from each major category were ordered
categories_w_purchases = []
items_purchased = []
num_categories = 0
num_items = 0
num_items_by_category = {}

for key, value in dict2.items():
  for a, b in value.items():
    if a not in categories_w_purchases:
      categories_w_purchases.append(a)
      num_categories += 1
    for item in b:
      if item not in items_purchased:
        items_purchased.append(item)
        num_items += 1
      if a not in num_items_by_category.keys():
        num_items_by_category[a] = 1
      else:
        num_items_by_category[a] += 1

print(categories_w_purchases)
print(items_purchased)
print(num_categories)
print(num_items)

['books', 'food', 'clothing', 'electronics']
['book1', 'book2', 'chips', 'tomatoes', 'socks', 'shirt', 'tv', 'phone']
4
8


In [65]:
dict2

{'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatoes']},
 'customer2': {'clothing': ['socks', 'shirt'], 'electronics': ['tv', 'phone']}}

In [ ]:
# numpy
arr1 = np.array(list1)
arr1

array([4000, 1000,   78,   15,   25,  100])

In [68]:
arr1.astype(float)

array([4000., 1000.,   78.,   15.,   25.,  100.])

In [79]:
arr1[0]

4000

In [76]:
arr1 = np.append(arr1, [500, 200, 100])

In [80]:
arr1.reshape(5,2)

ValueError: cannot reshape array of size 14 into shape (5,2)

In [82]:
arr2 = np.array([[12, 15, 78], [15, 25, 100], [4000, 100, 200]])

In [85]:
arr3 = np.array([10])

In [86]:
arr2 + arr3

array([[  22,   25,   88],
       [  25,   35,  110],
       [4010,  110,  210]])